# Dockerfile-backend
FROM python:3.8-slim-buster

WORKDIR /backend

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY .env ./

ENV MERAKI_API_KEY=YOUR_API_KEY
ENV MERAKI_ORG_ID=YOUR_ORG_ID
ENV VERKADA_API_KEY=YOUR_API_KEY
ENV VERKADA_ORG_ID=YOUR_ORG_ID
ENV EXPECTED_API_KEY=YOUR_CUSTOM_SUPER_SECRET_PASSWORD

# CMD ["python", "App.py"]

# Start Gunicorn
exec gunicorn -b 0.0.0.0:8000 App:app
