# Dockerfile-frontend
FROM node:14 AS build-stage

WORKDIR /frontend

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.17

COPY --from=build-stage /frontend/build/ /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
